name: Telegram Bot Runner

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"   # every 20 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: |
          npm install node-telegram-bot-api axios csv-parser json2csv cloudinary streamifier

      - name: 🚀 Run bot (5 hours)
        run: |
          echo "Starting bot..."
          timeout 5h node app.js || true